import { C } from '../constants/colors';
import { Cd, Hdr, Btn, SL } from '../components';

export function AddMeeting({ nav, tt, meetingChecks, setMeetingChecks }) {
  return <div><Hdr title="Additional Requirements Meeting" sub="Task 7 · Legal Advisor" right={<div style={{background:C.bWa,border:`1px solid ${C.wa}44`,borderRadius:8,padding:'8px 14px',fontSize:11,color:C.wa}}>Loop Task 6 → Task 9</div>}/><div style={{display:'flex',gap:20}}><Cd style={{flex:1,padding:20}}><SL>Outstanding Items</SL>{Object.entries(meetingChecks).filter(([,v])=>!v).map(([k])=>{const lb={offshore:'Offshore allocation — confirm 30% limit',derivatives:'Derivative use policy — define instruments'};return <div key={k} style={{padding:'12px 0',borderBottom:`1px solid ${C.bd}`,display:'flex',alignItems:'center',gap:10}}><span style={{color:C.wa}}>⚠</span><span style={{fontSize:13,color:C.tx}}>{lb[k]||k}</span></div>})}
      {Object.values(meetingChecks).every(Boolean)&&<div style={{color:C.ok,fontSize:13,padding:20,textAlign:'center'}}>All resolved ✓</div>}<SL style={{marginTop:20}}>Attendees</SL>{['Legal (Sarah vdB)','PM (Amahle Z.)','Compliance (Johan V.)','Director (Marcus S.)'].map(a=><div key={a} style={{display:'flex',alignItems:'center',gap:8,padding:'5px 0',fontSize:12,color:C.tx}}><span style={{color:C.ok}}>☑</span>{a}</div>)}</Cd>
      <Cd style={{flex:1,padding:20}}><SL>Meeting Notes</SL><textarea defaultValue="Offshore allocation: 30% limit confirmed per Reg 28. Derivatives: Exchange-traded futures for hedging only." style={{width:'100%',height:200,background:C.el,border:`1px solid ${C.bd}`,borderRadius:6,color:C.tx,padding:12,fontSize:13,resize:'vertical',lineHeight:1.7}}/></Cd></div>
      <div style={{display:'flex',justifyContent:'flex-end',gap:12,marginTop:20}}><Btn>Save</Btn><Btn primary onClick={()=>{setMeetingChecks({fica:true,portfolio:true,fees:true,offshore:true,derivatives:true});tt('All resolved. Proceeding.');nav('TASK_TRACKER')}}>Complete & Proceed →</Btn></div></div>;
}
