import { C } from '../constants/colors';
import { Cd, Hdr, Btn, Badge, SL } from '../components';

export function FicaVerification({ ficaDocs, setFicaDocs, curDoc, setCurDoc, ob, nav, tt }) {
  const cur=curDoc,sC=setCurDoc;const doc=ficaDocs.find(d=>d.id===cur)||ficaDocs[8];const vc=ficaDocs.filter(d=>d.status==='VERIFIED').length;
  return <div><Hdr title="Perform FICA Verification" sub="Task 17 · Legal Assistant" right={<span style={{fontSize:13,color:C.ac}}>{vc}/{ficaDocs.length} verified</span>}/><div style={{display:'flex',gap:4,marginBottom:16,flexWrap:'wrap'}}>{ficaDocs.map(d=><button key={d.id} onClick={()=>sC(d.id)} style={{padding:'6px 10px',borderRadius:'6px 6px 0 0',border:`1px solid ${cur===d.id?C.ac:C.bd}`,borderBottom:cur===d.id?`2px solid ${C.ac}`:`1px solid ${C.bd}`,background:cur===d.id?C.el:'transparent',color:cur===d.id?C.tx:C.t2,fontSize:10,cursor:'pointer',whiteSpace:'nowrap'}}>{d.status==='VERIFIED'?'✅':'⏳'} {d.name.split(' ').slice(0,2).join(' ')}…</button>)}</div>
    <div style={{display:'flex',gap:20}}><Cd style={{flex:1.5,overflow:'hidden'}}><div style={{background:C.el,padding:'12px 20px',borderBottom:`1px solid ${C.bd}`,fontSize:12,color:C.t2}}>Preview — {doc.file}</div><div style={{padding:40,textAlign:'center',minHeight:300,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}><div style={{width:80,height:100,background:C.el,border:`1px solid ${C.b2}`,borderRadius:4,display:'flex',alignItems:'center',justifyContent:'center',fontSize:24,marginBottom:16}}>📄</div><div style={{fontSize:14,color:C.tx,fontWeight:500}}>{doc.file}</div><div style={{fontSize:12,color:C.t2,marginTop:4}}>{doc.size} · {doc.date}</div></div></Cd>
      <Cd style={{flex:1,padding:20}}><div style={{fontSize:14,fontWeight:600,color:C.tx,marginBottom:16}}>Verification — {doc.name}</div>{['Original/certified','Within validity','Signatory matches','All fields complete','Notarisation'].map((ck,i)=><div key={i} style={{display:'flex',alignItems:'center',gap:10,padding:'8px 0',borderBottom:`1px solid ${C.bd}`}}><span style={{fontSize:14}}>{doc.status==='VERIFIED'||i<4?'☑':'☐'}</span><span style={{fontSize:13,color:i>=4&&doc.status!=='VERIFIED'?C.wa:C.tx}}>{ck}</span></div>)}<div style={{marginTop:16}}><SL>Screening</SL>{['KYC','Sanctions','PEP'].map(s=><div key={s} style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'8px 0',borderBottom:`1px solid ${C.bd}`}}><span style={{fontSize:13,color:C.tx}}>{s}</span>{doc.status==='VERIFIED'?<span style={{fontSize:11,color:C.ok}}>✅ Clear</span>:<button style={{padding:'4px 12px',background:C.el,border:`1px solid ${C.b2}`,color:C.t2,borderRadius:4,fontSize:11,cursor:'pointer'}}>Run</button>}</div>)}</div>
        <div style={{display:'flex',gap:12,marginTop:16}}><Btn danger style={{flex:1}}>✗ Flag</Btn><Btn primary style={{flex:1}} onClick={()=>{setFicaDocs(p=>p.map(d=>d.id===cur?{...d,status:'VERIFIED'}:d));tt(`${doc.name} verified`)}}>✓ Verify</Btn></div></Cd></div>
    <div style={{textAlign:'right',marginTop:16}}><Btn primary onClick={()=>nav('FICA_DECISION')}>Decision →</Btn></div></div>;
}
