import { C } from '../constants/colors';
import { Cd, Hdr, Btn, SL } from '../components';

export function MeetingScheduler({ nav, tt }) {
  const days=['Mon 20','Tue 21','Wed 22','Thu 23','Fri 24'];const slots=['09:00','10:00','11:00','12:00','13:00','14:00','15:00'];
  return <div><Hdr title="Schedule Stakeholder Engagement Session" sub="Task 4 · MIS"/><div style={{display:'flex',gap:20}}><Cd style={{width:220,padding:20,flexShrink:0}}><SL>Attendees</SL>{['ICM COO (Thabo N.)','Legal Advisor (Sarah vdB)','Legal Asst (Yvette D.)','Compliance (Johan V.)','Client Dir (Marcus S.)','PM (Amahle Z.)','Mgr Seg (David P.)','Finance (Riaan dP)'].map(a=><div key={a} style={{display:'flex',alignItems:'center',gap:8,padding:'5px 0',fontSize:12,color:C.tx}}><span style={{color:C.ok}}>☑</span>{a}</div>)}</Cd>
    <Cd style={{flex:1,padding:20}}><SL>Calendar — January 2025</SL><div style={{display:'grid',gridTemplateColumns:`60px repeat(5,1fr)`,gap:1,background:C.bd,borderRadius:8,overflow:'hidden'}}><div style={{background:C.el,padding:8}}/>{days.map(d=><div key={d} style={{background:C.el,padding:8,textAlign:'center',fontSize:11,color:C.tx,fontWeight:600}}>{d}</div>)}{slots.flatMap(s=>[<div key={s+'l'} style={{background:C.sf,padding:'8px 6px',fontSize:11,color:C.t2,textAlign:'right'}}>{s}</div>,...days.map(d=>{const hit=d==='Tue 21'&&s==='10:00';return <div key={d+s} style={{background:hit?'rgba(59,130,246,.15)':C.sf,padding:6,minHeight:28,border:hit?`1px solid ${C.ac}`:'none',borderRadius:hit?4:0,cursor:'pointer'}}>{hit&&<div style={{fontSize:10,color:C.ac,fontWeight:600}}>10:00–11:30<br/>Kick-off</div>}</div>})])}</div></Cd>
    <Cd style={{width:240,padding:20,flexShrink:0}}><SL>Agenda</SL>{['Welcome & intros (5 min)','Client overview (10 min)','FICA requirements — Legal (15 min)','Portfolio setup — Ops (15 min)','IMA timeline — Legal (10 min)','Task assignments (20 min)','Q&A (15 min)'].map((a,i)=><div key={i} style={{display:'flex',alignItems:'flex-start',gap:8,padding:'7px 0',borderBottom:`1px solid ${C.bd}`,fontSize:12,color:C.tx}}><span style={{color:C.t2,fontFamily:"'Source Code Pro','Fira Code',monospace",flexShrink:0}}>{i+1}.</span>{a}</div>)}</Cd></div>
    <div style={{display:'flex',justifyContent:'flex-end',gap:12,marginTop:20}}><Btn>Save Draft</Btn><Btn primary onClick={()=>{tt('MS Teams invite sent');nav('RESPONSIBILITY_BOARD')}}>Send Invite →</Btn></div></div>;
}
