import { C } from '../constants/colors';
import { Cd, Hdr, Btn, TH, TD } from '../components';

export function ProcessConfig({ configTab, setConfigTab, tt }) {
  const tab = configTab, sT = setConfigTab;
  return <div><Hdr title="Process Configuration" sub="Administration"/><div style={{display:'flex',gap:4,marginBottom:16}}>{['Escalation Rules','Email Templates','Deadlines'].map((t,i)=><button key={t} onClick={()=>sT(i)} style={{padding:'10px 20px',borderRadius:'8px 8px 0 0',border:`1px solid ${tab===i?C.ac:C.bd}`,borderBottom:tab===i?`2px solid ${C.ac}`:`1px solid ${C.bd}`,background:tab===i?C.el:'transparent',color:tab===i?C.tx:C.t2,fontSize:13,cursor:'pointer'}}>{t}</button>)}</div><Cd style={{borderRadius:'0 12px 12px 12px',padding:24}}>
    {tab===0&&<div><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr style={{borderBottom:`1px solid ${C.bd}`}}>{['Trigger','Condition','Notify','Priority'].map(h=><TH key={h}>{h}</TH>)}</tr></thead><tbody>{[['Any task overdue','> 3 days','ICM COO','High'],['FICA verification','> 5 days','COO + Compliance','Critical'],['IMA review','> 7 days','Legal + Director','Medium'],['Client docs','> 14 days','Director + MIS','Medium'],['Portfolio sign-off','Any > 5 days','CLO','High'],['Deposit','> 7 days past','Finance + COO','High']].map(([tg,cd,nt,pr])=><tr key={tg} style={{borderBottom:`1px solid ${C.bd}`}}><TD style={{fontWeight:500}}>{tg}</TD><TD style={{color:C.t2}}>{cd}</TD><TD style={{color:C.t2}}>{nt}</TD><td style={{padding:'12px 16px'}}><span style={{fontSize:11,padding:'3px 8px',borderRadius:4,background:pr==='Critical'?'rgba(239,68,68,.1)':pr==='High'?'rgba(245,158,11,.1)':'rgba(59,130,246,.1)',color:pr==='Critical'?C.no:pr==='High'?C.wa:C.ac}}>{pr}</span></td></tr>)}</tbody></table></div>}
    {tab===1&&<div>{['FICA Document Request','Onboarding Notification','IMA Distribution','Meeting Invite','Deposit Confirmation','Onboarding Complete'].map(tmpl=><div key={tmpl} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'14px 0',borderBottom:`1px solid ${C.bd}`}}><div><div style={{fontSize:13,color:C.tx,fontWeight:500}}>{tmpl}</div><div style={{fontSize:11,color:C.t2,marginTop:2}}>Last edited: Feb 2025</div></div><Btn>Edit</Btn></div>)}</div>}
    {tab===2&&<div><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr style={{borderBottom:`1px solid ${C.bd}`}}>{['Phase','Tasks','Default','Editable'].map(h=><TH key={h}>{h}</TH>)}</tr></thead><tbody>{[['Phase 1','1–5','5 days'],['Phase 2','6–10','10 days'],['Phase 3','11–26','15 days'],['Phase 4','27–37','20 days'],['Phase 5','38–55','30 days']].map(([ph,rng,dl])=><tr key={ph} style={{borderBottom:`1px solid ${C.bd}`}}><TD style={{fontWeight:500}}>{ph}</TD><TD style={{color:C.t2}}>{rng}</TD><td style={{padding:'12px 16px'}}><input defaultValue={dl} style={{width:90,padding:'6px 10px',background:C.el,border:`1px solid ${C.bd}`,borderRadius:4,color:C.tx,fontSize:13}}/></td><td style={{padding:'12px 16px'}}><span style={{color:C.ok,fontSize:11}}>✅</span></td></tr>)}</tbody></table></div>}
    </Cd><div style={{display:'flex',justifyContent:'flex-end',marginTop:20}}><Btn primary onClick={()=>tt('Saved')}>Save Config</Btn></div></div>;
}
