import { C } from '../constants/colors';
import { Cd, Hdr, Btn, Badge } from '../components';

export function SignoffChain({ ob, signoffs, setSignoffs, nav, tt }) {
  const multi=[{k:'comp_off',p:'Fatima Adams',r:'Compliance Officer'},{k:'crims',p:'Keanu Williams',r:'CRIMS'},{k:'data',p:'Sipho Mokoena',r:'Data Mgmt'},{k:'it',p:'Lerato Mofokeng',r:'IT DW'},{k:'fin',p:'Riaan du Plessis',r:'Finance'},{k:'risk',p:'Zanele Mokhele',r:'Risk'}];const mc=multi.filter(s=>signoffs[s.k]).length;
  return <div><Hdr title="Portfolio Sign-off Chain" sub={`${ob?.clientName} — SEG-2025-0047`}/><Cd style={{padding:24}}>
    {[{k:'clo',l:'CLO Sign-off (T29)',p:'Nomvula Khumalo',ts:'22 Jan 14:32'},{k:'manager',l:'Manager Review (T31)',p:'David Pietersen',ts:'23 Jan 09:15',cm:'Benchmark confirmed'}].map((s,i)=><div key={s.k} style={{display:'flex',gap:16,marginBottom:24,paddingBottom:24,borderBottom:`1px solid ${C.bd}`}}><div style={{width:36,height:36,borderRadius:'50%',background:signoffs[s.k]?C.ok:C.bd,display:'flex',alignItems:'center',justifyContent:'center',color:'#fff',fontSize:14,fontWeight:600,flexShrink:0}}>{signoffs[s.k]?'✓':i+1}</div><div style={{flex:1}}><div style={{fontSize:14,color:C.tx,fontWeight:600}}>{s.l}</div><div style={{fontSize:12,color:C.t2,marginTop:4}}>{s.p}</div>{signoffs[s.k]&&<div style={{fontSize:12,color:C.ok,marginTop:4}}>✅ SIGNED | {s.ts}</div>}{s.cm&&<div style={{fontSize:12,color:C.t2,marginTop:4,fontStyle:'italic'}}>"{s.cm}"</div>}</div></div>)}
    <div style={{display:'flex',gap:16,marginBottom:24,paddingBottom:24,borderBottom:`1px solid ${C.bd}`}}><div style={{width:36,height:36,borderRadius:'50%',background:mc===6?C.ok:C.ac,display:'flex',alignItems:'center',justifyContent:'center',color:'#fff',fontSize:14,fontWeight:600,flexShrink:0}}>3</div><div style={{flex:1}}><div style={{fontSize:14,color:C.tx,fontWeight:600,marginBottom:4}}>Multi-team Sign-off (T35)</div><div style={{fontSize:12,color:C.t2,marginBottom:12}}>{mc}/6 signed</div><div style={{background:C.el,borderRadius:8,padding:12}}>{multi.map(s=><div key={s.k} style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'8px 0',borderBottom:`1px solid ${C.bd}`}}><div><span style={{fontSize:13,color:C.tx}}>{s.p}</span><span style={{fontSize:11,color:C.t2,marginLeft:8}}>{s.r}</span></div>{signoffs[s.k]?<span style={{color:C.ok,fontSize:12}}>✅</span>:<div style={{display:'flex',gap:8}}><Btn style={{padding:'4px 10px',fontSize:11}} onClick={()=>tt(`Reminder → ${s.p}`)}>Remind</Btn><Btn primary style={{padding:'4px 10px',fontSize:11}} onClick={()=>setSignoffs(p=>({...p,[s.k]:true}))}>Sign</Btn></div>}</div>)}</div></div></div>
    {['Curo (T33–34)','Final CLO Sign-off','ICM Notification (T37)'].map((s,i)=><div key={s} style={{display:'flex',gap:16,marginBottom:i<2?24:0,paddingBottom:i<2?24:0,borderBottom:i<2?`1px solid ${C.bd}`:'none'}}><div style={{width:36,height:36,borderRadius:'50%',background:C.bd,display:'flex',alignItems:'center',justifyContent:'center',color:C.t2,fontSize:14,fontWeight:600,flexShrink:0}}>{i+4}</div><div><div style={{fontSize:14,color:C.t2}}>{s}</div><div style={{fontSize:12,color:C.t2,marginTop:4}}>○ NOT YET REACHED</div></div></div>)}
  </Cd>{mc===6&&<div style={{textAlign:'right',marginTop:16}}><Btn primary onClick={()=>nav('CURO_HANDOFF')}>Curo Handoff →</Btn></div>}</div>;
}
